//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub mod prelude;

mod orm;

pub mod t_admin;
pub mod t_choose;
pub mod t_class;
pub mod t_coach;
pub mod t_institute;
pub mod t_major;
pub mod t_major_limit;
pub mod t_middle;
pub mod t_review;
pub mod t_start;
pub mod t_student;
pub mod t_teacher;
pub mod t_thesis;
