//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::t_admin::Entity as TAdmin;
pub use super::t_choose::Entity as TChoose;
pub use super::t_class::Entity as TClass;
pub use super::t_coach::Entity as TCoach;
pub use super::t_institute::Entity as TInstitute;
pub use super::t_major::Entity as TMajor;
pub use super::t_major_limit::Entity as TMajorLimit;
pub use super::t_middle::Entity as TMiddle;
pub use super::t_review::Entity as TReview;
pub use super::t_start::Entity as TStart;
pub use super::t_student::Entity as TStudent;
pub use super::t_teacher::Entity as TTeacher;
pub use super::t_thesis::Entity as TThesis;
