//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "t_major_limit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sub_id: Option<i32>,
    #[sea_orm(column_name = "Major01")]
    pub major01: Option<i32>,
    #[sea_orm(column_name = "Major02")]
    pub major02: Option<i32>,
    #[sea_orm(column_name = "Major03")]
    pub major03: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
