//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "t_middle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub stu_code: Option<String>,
    pub teacher_code: Option<String>,
    pub thesis_id: Option<i32>,
    pub content: Option<String>,
    pub time: Option<DateTime>,
    pub other: Option<String>,
    pub place: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
